### ISSUE TITLE
Would it be possible to use it as an inline element instead of the default behaviour ie. popping up from below as a modal? :label-question

### ISSUE THREAD

**Issue by nihal31** [swenyang/react-ultra-select#2]

**Comment by swenyang** [comment]
Actually it's possible, however in mobile devices an inline scroll-to-select element takes too much space, and its scrolling conflicts with the page's scrolling. This kind of UI experience sucks, especially on small screens.

**Comment by swenyang** [comment]
I think it's good to separate component's the inline part with the modal(i.e. it only handles the modal), not making the modal inline.

**Comment by nihal31** [comment]
Thanks for the prompt reply. My specific usecase was for an Ipad screen where the screen is big and it makes sense to have the component as inline. Since you said that it is possible, I will look through the code. Any pointers on how to get started?

**Comment by swenyang** [comment]
In that case you should just remove the inline part(i.e. `renderStatic`), the backdrop and the `Portal`, then change the style of the modal from fixed to inline. Here is an [online example](http://elemefe.github.io/mint-ui/#/picker), I think which is what you want, however written by Vue.js.

**Comment by nihal31** [comment]
Great help. Thanks
